### ISSUE TITLE
Log Guid and/or MD5 hash of assemblies

### ISSUE THREAD

**Issue by originalfoo** [CitiesSkylinesMods/DuplicateAssemblyScanner#12]
It's possible that assemblies report the same version but are in fact different (eg. tweaked code) - see: https://github.com/CitiesSkylinesMods/DuplicateAssemblyScanner/issues/8#issuecomment-595010506

In the log file, we should at least log some additional detail that helps track down assemblies with same version but different code.

**Comment by krzychu124** [comment]
I don't think you would even need that considering my comment https://github.com/CitiesSkylinesMods/DuplicateAssemblyScanner/issues/9#issuecomment-595331768 😉

**Comment by originalfoo** [comment]
Kian mentioned that some `0Harmony.dll` are tweaked by mod author but have same verison number as "official" release. So the md5 is a double check to see if any dlls report same version but have different code.

**Comment by krzychu124** [comment]
I think if you use **PluginManager.m_AssemblyLocations** you should get both versions because modified Assembly should be different that original one and Assembly is Dictionary.Key (no duplicated). I'm not really sure but it's worth checking if Equals() will return true only for exact same assemblies or not.

**Comment by originalfoo** [comment]
Here's evidence of tweaked Harmony dll:

```
[Info]    > 1.1.0.0 9b81c76b538fc2217f8df27d4d76685f /1412844620   Realistic Walking Speed
[Info]      1.1.0.0 c0d7618949db5ae9bb0a6dda04b82769 /870291141    Random Train Trailers 2.1.2
```

Both v1.1.0.0, but the MD5 hash after version number shows there's a difference.
