### ISSUE TITLE
Check if Assembly.GetName().GetHashCode() is alternative to MD5 hash

### ISSUE THREAD

**Issue by originalfoo** [CitiesSkylinesMods/DuplicateAssemblyScanner#15]
Not had time to check yet, but just noticed the `GetHashCode()` method - maybe it's a better alternative to MD5 hashing the file on disk?

**Comment by krzychu124** [comment]
No it's not :/ It's completely different thing and cannot be used for comparison of files, afaik. Hashcode is mainly used to check equality of instances e.g: when object is a `Key` for `Hashtable`. 
Ideally it should be unique, you can and sometimes shoul override default implementation and build your own based on field values of object.
You can imagine what would happen when you use mutable type as a `Key` of dictionary. 
One change in that mutable object will make dictionary `Value` inaccessible using previously set `Key` or worse, you would overwrite the other `Value` using "new `Key`" if returns the same hashcode as previously added.
