### ISSUE TITLE
Rescan after mod subscription changes

### ISSUE THREAD

**Issue by originalfoo** [CitiesSkylinesMods/DuplicateAssemblyScanner#3]
Will need to work out how to refresh the settings screen....

**Comment by krzychu124** [comment]
I think there is an event named `eventPluginsChanged` or something like that

**Comment by originalfoo** [comment]
There is, but I have no idea how to reset the settings screen once it's already been created.

**Comment by krzychu124** [comment]
You need to add boilerplate code (basically refactor it) to be able to recreate it on demand, sadly

**Comment by originalfoo** [comment]
Every time a mod is enabled/disabled/subscribed/unsubscrined the game recreates settings for all mods - ugh, but also means I don't need any additional stuff to handle that situation.
