### ISSUE TITLE
Scan mod folder if PluginInfo doesn't mention assembly

### ISSUE THREAD

**Issue by originalfoo** [CitiesSkylinesMods/DuplicateAssemblyScanner#9]
This is primarily for detection of Harmony assemblies that didn't get loaded (not sure how that works, but guessing it's due to assembly Guid, asembly version and assembly file version all matching).

The `PluginInfo.GetAssemblies()` only lists assemblies that were loaded in to the app domain.

If the assembly we're looking for isn't listed in there, we should scan the mod folder as a fallback check to see if mod still contains the assembly.

This should only be done for `0Harmony` assemblies (at least initially) as that is of key importance to detecting mods that use Harmony.

**Comment by originalfoo** [comment]
how to get assembly name (which includes lots of useful stuff) for assembly on disk without loading it in to app domain:

```cs
AssemblyName asmName = AssemblyName.GetAssemblyName(fullPath);
```

**Comment by krzychu124** [comment]
> If the assembly we're looking for isn't listed in there, we should scan the mod folder as a fallback check to see if mod still contains the assembly.

Afaik it's impossible. The only case when assembly is not loaded to AppDomain is when someone dropped `dll` to mod folder but didn't reference it in project. 
It doesn't matter if mod is enabled or disabled, it will be always loaded to AppDomain along with it's dependecies, and **all** dlls are loaded earlier to `ReflectionOnly` context(sort of read only image - cannot be executed): 
- **LoadAssembliesRO()** `string[] files = Directory.GetFiles(modPath, "*.dll", SearchOption.AllDirectories);`

**PluginManager.m_AssemblyLocations** _(Dictionary<Assembly, string>)_ contains all previously found assemblies (loaded to `RefrectionOnly` context). You can read Assembly name _(Dictionary.Key)_ and get path _(Dictionary.Value)_

**Comment by originalfoo** [comment]
@krzychu124 That's not the case with `0Harmony` - it seems like it won't get loaded a second time if an already loaded assembly has the same file version in its assembly info.

Kian mentioned this in https://github.com/CitiesSkylinesMods/DuplicateAssemblyScanner/issues/8#issuecomment-595010506 and I've checked and confirmed that it does appear that the game isn't loading _all_ `0Harmony.dll` in to app domain, only the first ones it encounters with a specific file version.

I'm currently refactoring the assembly scanner now to gather full details; should be ready later this evening.

**Comment by originalfoo** [comment]
Just re-read your comment; will try that too :)

**Comment by originalfoo** [comment]
Here's what the dictionary contains for me:

EDIT: Trimmed to entries for Harmony:

```
[Info]  DuplicateAssemblyScanner v1.1.0.35160
[Info]  Enabled
[Info]  SettingsUI
[Info]  Scanning app domain assemblies for duplicates...
[Info]  C:\Program Files (x86)\Steam\steamapps\workshop\content\255710\1886877404\0Harmony.dll
[Info]  C:\Program Files (x86)\Steam\steamapps\workshop\content\255710\1562650024\0Harmony.dll
[Info]  C:\Program Files (x86)\Steam\steamapps\workshop\content\255710\1412844620\0Harmony.dll
[Info]  C:\Program Files (x86)\Steam\steamapps\workshop\content\255710\1386697922\0Harmony.dll
[Info]  C:\Program Files (x86)\Steam\steamapps\workshop\content\255710\1758376843\0Harmony.dll
[Info]  Disabled
```

**Comment by originalfoo** [comment]
@krzychu124 It looks like even the `PluginManager.m_AssemblyLocations` isn't loading duplicate Harmonies. So I'm still going to have to do manual directory search.

**Comment by originalfoo** [comment]
It's alive!! This conclusively confirmes what @kianzarrin said: Only one version of each Harmony assembly is getting loaded:

EDIT: Updated. `*` = Mod enabled. `>` = Assembly loaded.

```
[Info]  0Harmony found in:
[Info]  *   1.2.0.1 /1899640536   Theme Mixer 2
[Info]  *   1.2.0.1 /877950833    Vanilla Trees Remover
[Info]  *   1.2.0.1 /1806759255   Customize It! Extended
[Info]  *   1.2.0.1 /1869561285   Prop Painter
[Info]  *   1.2.0.1 /1764637396   Toggle It!
[Info]  *   1.2.0.1 /1801953480   Natural Disasters Overhaul
[Info]  *   1.2.0.1 /1794015399   Render It!
[Info]  *   1.2.0.1 /552309905    No Abandonment
[Info]  *   1.2.0.1 /1567569285   Achieve It!
[Info]  *   1.2.0.1 /1721492498   Optimised Outside Connections
[Info]  * > 1.2.0.2 /1562650024   Rebalanced Industries
[Info]  *   1.2.0.1 /1591417160   Hide It!
[Info]  *   1.2.0.1 /1658679290   Forest Brush
[Info]  *   1.2.0.1 /1680642819   Ultimate Level Of Detail
[Info]      1.1.0.0 /870291141    Random Train Trailers 2.1.2
[Info]    > 1.1.0.0 /1412844620   Realistic Walking Speed
[Info]  *   1.2.0.1 /1420955187   Real Time
[Info]  *   1.2.0.1 /924884948    Plop Growables
[Info]  *   1.2.0.1 /1435741602   Snooper
[Info]  *   1.0.9.1 /1372431101   Painter
[Info]  * > 1.0.9.1 /1386697922   Garbage Bin Controller
[Info]  *   1.2.0.1 /1938493221   Mini FPS Booster 1.0
[Info]  * > 1.2.0.1 /1886877404   Custom Effect Loader
[Info]  * > 2.0.0.0 /1758376843   Network Skins 2 Beta
```

**Comment by dymanoid** [comment]
@aubergine10 This is not 100% correct. There *are* multiple copies of the same version in the app domain. However, some of them are in the Reflection Only context.
Look at this:
![harmony](https://user-images.githubusercontent.com/9433345/76028128-375bfb80-5f32-11ea-8d25-ca681175cd8c.PNG)
I marked the Harmony modules. There are two of version 1.2.0.1 (Real Time, Snooper, More Vehicles) and two of version 2.0.0.0 (NS2 Beta). There are two of version 1.9.9.9 too (CSUR, not highlighted).

**Comment by originalfoo** [comment]
@dymanoid Yes, i think the duplciates of _same version_ are in the `ReflectionOnly` context. But each version is only getting loaded once per context (assuming the app domain is a "context" - not quite sure of the terminology).

**Comment by dymanoid** [comment]
@aubergine10 The load context and the app domain are different kinds of things. There are several load contexts which all apply for every app domain. In the game, we only have one single app domain, so let's forget about multiple app domains. We only can have multiple load contexts:
- reflection only
- default
- load-from
- no context

As it turns out, the game loads the assemblies into one of the two contexts: *reflection only* or/and *default*.
